---
title: "R for Data Science"
author: "Duzhe Wang"
date: "3/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Chapter 3: Data visualization (ggplot2)

```{r}
mpg
ggplot(data=mpg)+geom_point(mapping=aes(x=displ, y=hwy))
#ggplot(data = <DATA>) + 
#GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
```


## Chapter 5: Data transformation 

```{r}
library(nycflights13)
nycflights13::flights

## tibbles are data frames, but slightly tweaked to work better in the tidyverse. 
## int: integers
## dbl: double
## chr: characters
## dttm: date-times 
## lgl: logical
## fctr: factors 
## date: dates 
```


### filter( )

```{r}
(jan1<-filter(flights, month==1, day==1))
```


```{r}
filter(flights, month==11|month==12)
```


```{r}
filter(flights, month%in% c(11, 12))
```

```{r}
# filter only includes rows where the condition is TRUE.
df<-tibble(x=c(1, NA, 3))
filter(df, x>1)
filter(df, is.na(x)|x>1)
```

### arrange()

```{r}
df<-tibble(x=c(5,2,NA))
arrange(df, x)
# missing value always in the end 
```

### select(): select variables 

```{r}
select(flights, year, month, day)
```


### Add new variables with mutate()

```{r}
flights_sml<-select(flights, year:day, ends_with("delay"), distance, air_time)
mutate(flights_sml, gain=dep_delay-arr_delay, speed=distance/air_time*60)
```

### Only keep the new variables with transmute()

```{r}
transmute(flights, gain=dep_delay-arr_delay, hours=air_time/60, gain_per_hour=gain/hours)
```


### Summarise()

```{r}
summarise(flights, delay=mean(dep_delay, na.rm=TRUE))
```

```{r}
(by_day<-group_by(flights, year, month, day))
## group doesn't change how the data looks. It changes how it acts with the other dplyr verbs. 

summarise(by_day, delay=mean(dep_delay, na.rm=TRUE))
```


### Combining multiple operations with the pipe

```{r}
by_dest<-group_by(flights, dest)
(delay<-summarise(by_dest, 
                 count=n(), # number of rows for each destination
                 dist=mean(distance, na.rm=TRUE),
                 delay=mean(arr_delay, na.rm=TRUE)
                 ))
(delay<-filter(delay, count>20, dest!="HNL"))

ggplot(data=delay, mapping=aes(x=dist, y=delay))+
  geom_point(aes(size=count), alpha=1/3)+
  geom_smooth(se=FALSE)
```

Another much better way:

```{r}
(delays<-flights %>%
        group_by(dest)%>%
        summarise(
          count=n(),
          dist=mean(distance, na.rm=TRUE),  ## remove missing values 
          delay=mean(arr_delay, na.rm=TRUE)
        ) %>%
 filter(count>20, dest!="HNL")
)
 delays %>%  
   ggplot(mapping=aes(x=dist, y=delay))+
   geom_point(alpha=1)

```

```{r}
flights%>%
  group_by(year, month, day) %>%
  summarise(flights=n())
```


### ungrouping 

```{r}
by_day=flights%>%
         group_by(year, month, day)
ungroupdata=by_day %>%
         ungroup()
summarise(ungroupdata, n=n())
```





































